// Product seed data — images sourced from Unsplash
// categorySlug field will be resolved to ObjectId in the seed runner

const products = [
  // ===================== CAKES =====================
  {
    name: 'Classic Chocolate Truffle Cake',
    slug: 'classic-chocolate-truffle-cake',
    description: 'Rich, indulgent chocolate truffle cake layered with smooth ganache. Perfect for birthdays and celebrations. Made with premium Belgian cocoa.',
    shortDescription: 'Rich chocolate truffle cake with Belgian cocoa',
    categorySlug: 'celebration-cakes',
    images: [
      { url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&q=80', alt: 'Chocolate truffle cake', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=800&q=80', alt: 'Chocolate cake slice', isPrimary: false },
    ],
    variants: [
      { size: '0.5 kg', weight: '500g', price: 449, compareAtPrice: 549, sku: 'CTC-500' },
      { size: '1 kg', weight: '1kg', price: 799, compareAtPrice: 999, sku: 'CTC-1000' },
      { size: '2 kg', weight: '2kg', price: 1499, compareAtPrice: 1799, sku: 'CTC-2000' },
    ],
    dietaryTags: ['eggless', 'veg'],
    isShippable: false,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: '2 days (refrigerated)',
    ingredients: 'Flour, cocoa powder, sugar, butter, cream, Belgian chocolate, vanilla extract',
    isFeatured: true,
    sortOrder: 1,
    ratings: { average: 4.7, count: 234 },
  },
  {
    name: 'Red Velvet Dream Cake',
    slug: 'red-velvet-dream-cake',
    description: 'Stunning red velvet cake with velvety cream cheese frosting. A visual and culinary delight for any special occasion.',
    shortDescription: 'Classic red velvet with cream cheese frosting',
    categorySlug: 'celebration-cakes',
    images: [
      { url: 'https://images.unsplash.com/photo-1616541823729-00fe0aacd32c?w=800&q=80', alt: 'Red velvet cake', isPrimary: true },
    ],
    variants: [
      { size: '0.5 kg', weight: '500g', price: 499, compareAtPrice: 599, sku: 'RVC-500' },
      { size: '1 kg', weight: '1kg', price: 899, compareAtPrice: 1099, sku: 'RVC-1000' },
      { size: '2 kg', weight: '2kg', price: 1699, compareAtPrice: 1999, sku: 'RVC-2000' },
    ],
    dietaryTags: ['eggless', 'veg'],
    isShippable: false,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: '2 days (refrigerated)',
    isFeatured: true,
    sortOrder: 2,
    ratings: { average: 4.8, count: 189 },
  },
  {
    name: 'Butterscotch Crunch Cake',
    slug: 'butterscotch-crunch-cake',
    description: 'Luscious butterscotch flavoured cake topped with caramelized praline crunch and butterscotch drizzle.',
    shortDescription: 'Butterscotch cake with praline crunch topping',
    categorySlug: 'celebration-cakes',
    images: [
      { url: 'https://images.unsplash.com/photo-1621303837174-89787a7d4729?w=800&q=80', alt: 'Butterscotch cake', isPrimary: true },
    ],
    variants: [
      { size: '0.5 kg', weight: '500g', price: 399, compareAtPrice: 499, sku: 'BSC-500' },
      { size: '1 kg', weight: '1kg', price: 749, compareAtPrice: 899, sku: 'BSC-1000' },
    ],
    dietaryTags: ['eggless', 'veg'],
    isShippable: false,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: '2 days (refrigerated)',
    isFeatured: false,
    sortOrder: 3,
    ratings: { average: 4.5, count: 156 },
  },
  {
    name: 'Black Forest Cake',
    slug: 'black-forest-cake',
    description: 'Traditional Black Forest cake with layers of chocolate sponge, whipped cream, and cherries. Topped with chocolate shavings.',
    shortDescription: 'Classic Black Forest with cherries & cream',
    categorySlug: 'celebration-cakes',
    images: [
      { url: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=800&q=80', alt: 'Black Forest cake', isPrimary: true },
    ],
    variants: [
      { size: '0.5 kg', weight: '500g', price: 449, sku: 'BFC-500' },
      { size: '1 kg', weight: '1kg', price: 849, sku: 'BFC-1000' },
      { size: '2 kg', weight: '2kg', price: 1599, sku: 'BFC-2000' },
    ],
    dietaryTags: ['eggless', 'veg'],
    isShippable: false,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: '2 days (refrigerated)',
    isFeatured: true,
    sortOrder: 4,
    ratings: { average: 4.6, count: 312 },
  },
  {
    name: 'Pineapple Fresh Cream Cake',
    slug: 'pineapple-fresh-cream-cake',
    description: 'Light and fluffy vanilla sponge layered with fresh pineapple chunks and whipped cream.',
    shortDescription: 'Fresh pineapple cake with whipped cream',
    categorySlug: 'celebration-cakes',
    images: [
      { url: 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=800&q=80', alt: 'Pineapple cake', isPrimary: true },
    ],
    variants: [
      { size: '0.5 kg', weight: '500g', price: 349, sku: 'PFC-500' },
      { size: '1 kg', weight: '1kg', price: 649, sku: 'PFC-1000' },
    ],
    dietaryTags: ['eggless', 'veg'],
    isShippable: false,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: '2 days (refrigerated)',
    sortOrder: 5,
    ratings: { average: 4.4, count: 198 },
  },
  {
    name: 'Mango Delight Cake',
    slug: 'mango-delight-cake',
    description: 'Seasonal favourite! Fresh Alphonso mango pulp layered cake with mango cream frosting. Available during mango season.',
    shortDescription: 'Fresh Alphonso mango layered cake',
    categorySlug: 'celebration-cakes',
    images: [
      { url: 'https://images.unsplash.com/photo-1557979619-445218f326b9?w=800&q=80', alt: 'Mango cake', isPrimary: true },
    ],
    variants: [
      { size: '0.5 kg', weight: '500g', price: 499, sku: 'MDC-500' },
      { size: '1 kg', weight: '1kg', price: 949, sku: 'MDC-1000' },
    ],
    dietaryTags: ['eggless', 'veg'],
    isShippable: false,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: '2 days (refrigerated)',
    isFeatured: true,
    sortOrder: 6,
    ratings: { average: 4.9, count: 89 },
  },

  // ===================== BAKERY — COOKIES =====================
  {
    name: 'Chocolate Chip Cookies Pack',
    slug: 'chocolate-chip-cookies-pack',
    description: 'Crispy on the outside, chewy on the inside. Loaded with premium chocolate chips. Perfect with a cup of chai or coffee.',
    shortDescription: 'Classic chocolate chip cookies, pack of 12',
    categorySlug: 'cookies-packs',
    images: [
      { url: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&q=80', alt: 'Chocolate chip cookies', isPrimary: true },
    ],
    variants: [
      { size: '200g', weight: '200g', price: 149, compareAtPrice: 179, sku: 'CCC-200' },
      { size: '400g', weight: '400g', price: 269, compareAtPrice: 329, sku: 'CCC-400' },
    ],
    dietaryTags: ['eggless', 'veg'],
    isShippable: true,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: '30 days',
    ingredients: 'Refined flour, butter, sugar, chocolate chips, vanilla, baking soda',
    isFeatured: true,
    sortOrder: 1,
    ratings: { average: 4.6, count: 445 },
  },
  {
    name: 'Oatmeal Raisin Cookies',
    slug: 'oatmeal-raisin-cookies',
    description: 'Wholesome oatmeal cookies studded with plump raisins. A healthier treat that doesn\'t compromise on taste.',
    shortDescription: 'Healthy oatmeal cookies with raisins',
    categorySlug: 'cookies-packs',
    images: [
      { url: 'https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e?w=800&q=80', alt: 'Oatmeal cookies', isPrimary: true },
    ],
    variants: [
      { size: '200g', weight: '200g', price: 129, sku: 'ORC-200' },
      { size: '400g', weight: '400g', price: 229, sku: 'ORC-400' },
    ],
    dietaryTags: ['eggless', 'veg'],
    isShippable: true,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: '30 days',
    sortOrder: 2,
    ratings: { average: 4.3, count: 178 },
  },
  {
    name: 'Almond Biscotti',
    slug: 'almond-biscotti',
    description: 'Italian-style twice-baked almond biscotti. Crunchy, aromatic, and perfect for dipping in coffee.',
    shortDescription: 'Crunchy Italian almond biscotti',
    categorySlug: 'cookies-packs',
    images: [
      { url: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&q=80', alt: 'Almond biscotti', isPrimary: true },
    ],
    variants: [
      { size: '150g', weight: '150g', price: 199, sku: 'AB-150' },
      { size: '300g', weight: '300g', price: 369, sku: 'AB-300' },
    ],
    dietaryTags: ['eggless', 'veg'],
    isShippable: true,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: '45 days',
    isFeatured: true,
    sortOrder: 3,
    ratings: { average: 4.5, count: 93 },
  },
  {
    name: 'Coconut Cookies Pack',
    slug: 'coconut-cookies-pack',
    description: 'Buttery cookies loaded with desiccated coconut. Melt-in-your-mouth texture with a tropical twist.',
    shortDescription: 'Buttery coconut cookies, pack of 12',
    categorySlug: 'cookies-packs',
    images: [
      { url: 'https://images.unsplash.com/photo-1618923850107-d1a234ef2c18?w=800&q=80', alt: 'Coconut cookies', isPrimary: true },
    ],
    variants: [
      { size: '200g', weight: '200g', price: 119, sku: 'CC-200' },
    ],
    dietaryTags: ['eggless', 'veg'],
    isShippable: true,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: '30 days',
    sortOrder: 4,
    ratings: { average: 4.2, count: 134 },
  },

  // ===================== BAKERY — CREAM ROLLS =====================
  {
    name: 'Chocolate Dip Cream Roll',
    slug: 'chocolate-dip-cream-roll',
    description: 'Flaky puff pastry roll filled with fresh vanilla cream, dipped in rich chocolate coating.',
    shortDescription: 'Cream-filled puff roll with chocolate dip',
    categorySlug: 'cream-rolls',
    images: [
      { url: 'https://images.unsplash.com/photo-1509365465985-25d11c17e812?w=800&q=80', alt: 'Chocolate cream roll', isPrimary: true },
    ],
    variants: [
      { size: 'Single', weight: '80g', price: 49, sku: 'CDCR-1' },
      { size: 'Pack of 4', weight: '320g', price: 179, compareAtPrice: 196, sku: 'CDCR-4' },
    ],
    dietaryTags: ['eggless', 'veg'],
    isShippable: false,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: '2 days',
    sortOrder: 1,
    ratings: { average: 4.4, count: 267 },
  },
  {
    name: 'Butterscotch Cream Roll',
    slug: 'butterscotch-cream-roll',
    description: 'Crispy puff pastry filled with butterscotch-flavoured cream and caramel praline crunch.',
    shortDescription: 'Butterscotch cream-filled puff roll',
    categorySlug: 'cream-rolls',
    images: [
      { url: 'https://images.unsplash.com/photo-1530610476181-d83430b64dcd?w=800&q=80', alt: 'Butterscotch cream roll', isPrimary: true },
    ],
    variants: [
      { size: 'Single', weight: '80g', price: 45, sku: 'BSCR-1' },
      { size: 'Pack of 4', weight: '320g', price: 165, sku: 'BSCR-4' },
    ],
    dietaryTags: ['eggless', 'veg'],
    isShippable: false,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: '2 days',
    sortOrder: 2,
    ratings: { average: 4.3, count: 189 },
  },

  // ===================== BAKERY — TEA CAKES =====================
  {
    name: 'Honey Almond Tea Cake',
    slug: 'honey-almond-tea-cake',
    description: 'Moist, honey-infused tea cake topped with toasted almond slivers. Perfect afternoon companion.',
    shortDescription: 'Moist honey cake with toasted almonds',
    categorySlug: 'tea-cakes',
    images: [
      { url: 'https://images.unsplash.com/photo-1464305795204-6f5bbfc7fb81?w=800&q=80', alt: 'Honey almond tea cake', isPrimary: true },
    ],
    variants: [
      { size: '250g', weight: '250g', price: 179, sku: 'HATC-250' },
      { size: '500g', weight: '500g', price: 329, sku: 'HATC-500' },
    ],
    dietaryTags: ['eggless', 'veg'],
    isShippable: true,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: '7 days',
    isFeatured: true,
    sortOrder: 1,
    ratings: { average: 4.7, count: 156 },
  },
  {
    name: 'Fruit Cake',
    slug: 'fruit-cake',
    description: 'Traditional fruit cake loaded with candied fruits and nuts. Rich, dense, and packed with flavour.',
    shortDescription: 'Traditional fruit & nut cake',
    categorySlug: 'tea-cakes',
    images: [
      { url: 'https://images.unsplash.com/photo-1603532648955-039310d9ed75?w=800&q=80', alt: 'Fruit cake', isPrimary: true },
    ],
    variants: [
      { size: '250g', weight: '250g', price: 199, sku: 'FC-250' },
      { size: '500g', weight: '500g', price: 369, sku: 'FC-500' },
    ],
    dietaryTags: ['eggless', 'veg'],
    isShippable: true,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: '10 days',
    sortOrder: 2,
    ratings: { average: 4.4, count: 201 },
  },

  // ===================== BAKERY — BREADS =====================
  {
    name: 'Multigrain Bread Loaf',
    slug: 'multigrain-bread-loaf',
    description: 'Hearty multigrain bread made with whole wheat, oats, flax seeds, and sunflower seeds. Freshly baked daily.',
    shortDescription: 'Fresh multigrain bread with seeds',
    categorySlug: 'breads-buns',
    images: [
      { url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80', alt: 'Multigrain bread', isPrimary: true },
    ],
    variants: [
      { size: 'Regular', weight: '400g', price: 79, sku: 'MGB-400' },
    ],
    dietaryTags: ['eggless', 'veg'],
    isShippable: false,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: '3 days',
    sortOrder: 1,
    ratings: { average: 4.5, count: 89 },
  },
  {
    name: 'Garlic Herb Focaccia',
    slug: 'garlic-herb-focaccia',
    description: 'Italian-style flatbread infused with roasted garlic, rosemary, and olive oil. Crusty on the outside, fluffy inside.',
    shortDescription: 'Roasted garlic & rosemary focaccia',
    categorySlug: 'breads-buns',
    images: [
      { url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80', alt: 'Garlic focaccia bread', isPrimary: true },
    ],
    variants: [
      { size: 'Regular', weight: '300g', price: 149, sku: 'GHF-300' },
    ],
    dietaryTags: ['eggless', 'veg'],
    isShippable: false,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: '2 days',
    sortOrder: 2,
    ratings: { average: 4.6, count: 67 },
  },

  // ===================== BAKERY — BROWNIES =====================
  {
    name: 'Classic Fudge Brownie',
    slug: 'classic-fudge-brownie',
    description: 'Dense, fudgy chocolate brownie with a crackly top. Made with premium dark chocolate for an intense cocoa experience.',
    shortDescription: 'Dense dark chocolate fudge brownie',
    categorySlug: 'dry-cakes-brownies',
    images: [
      { url: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&q=80', alt: 'Chocolate fudge brownie', isPrimary: true },
    ],
    variants: [
      { size: 'Single', weight: '80g', price: 89, sku: 'CFB-1' },
      { size: 'Box of 4', weight: '320g', price: 329, compareAtPrice: 356, sku: 'CFB-4' },
      { size: 'Box of 8', weight: '640g', price: 599, compareAtPrice: 712, sku: 'CFB-8' },
    ],
    dietaryTags: ['eggless', 'veg'],
    isShippable: true,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: '7 days',
    isFeatured: true,
    sortOrder: 1,
    ratings: { average: 4.8, count: 523 },
  },
  {
    name: 'Walnut Brownie',
    slug: 'walnut-brownie',
    description: 'Our signature fudge brownie loaded with crunchy walnut pieces. The perfect balance of chocolate and nuts.',
    shortDescription: 'Fudge brownie loaded with walnuts',
    categorySlug: 'dry-cakes-brownies',
    images: [
      { url: 'https://images.unsplash.com/photo-1607920591413-4ec007e70023?w=800&q=80', alt: 'Walnut brownie', isPrimary: true },
    ],
    variants: [
      { size: 'Single', weight: '80g', price: 109, sku: 'WB-1' },
      { size: 'Box of 4', weight: '320g', price: 399, sku: 'WB-4' },
    ],
    dietaryTags: ['eggless', 'veg'],
    isShippable: true,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: '7 days',
    sortOrder: 2,
    ratings: { average: 4.7, count: 198 },
  },

  // ===================== BAKERY — PASTRIES =====================
  {
    name: 'Butter Croissant',
    slug: 'butter-croissant',
    description: 'Flaky, golden, buttery croissant baked fresh every morning. Light and airy with a beautiful laminated structure.',
    shortDescription: 'Freshly baked French butter croissant',
    categorySlug: 'pastries-patties',
    images: [
      { url: 'https://images.unsplash.com/photo-1530610476181-d83430b64dcd?w=800&q=80', alt: 'Butter croissant', isPrimary: true },
    ],
    variants: [
      { size: 'Single', weight: '70g', price: 79, sku: 'BC-1' },
      { size: 'Pack of 3', weight: '210g', price: 219, compareAtPrice: 237, sku: 'BC-3' },
    ],
    dietaryTags: ['eggless', 'veg'],
    isShippable: false,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: '1 day',
    isFeatured: true,
    sortOrder: 1,
    ratings: { average: 4.5, count: 334 },
  },
  {
    name: 'Veg Puff Patty',
    slug: 'veg-puff-patty',
    description: 'Crispy puff pastry filled with spiced mixed vegetable filling. A classic Indian bakery favourite.',
    shortDescription: 'Crispy puff pastry with spiced veg filling',
    categorySlug: 'pastries-patties',
    images: [
      { url: 'https://images.unsplash.com/photo-1517433670267-08bbd4be890f?w=800&q=80', alt: 'Veg puff patty', isPrimary: true },
    ],
    variants: [
      { size: 'Single', weight: '100g', price: 35, sku: 'VPP-1' },
      { size: 'Pack of 4', weight: '400g', price: 129, compareAtPrice: 140, sku: 'VPP-4' },
    ],
    dietaryTags: ['eggless', 'veg'],
    isShippable: false,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: '1 day',
    sortOrder: 2,
    ratings: { average: 4.3, count: 567 },
  },

  // ===================== BAKERY — RUSKS =====================
  {
    name: 'Elaichi Rusk',
    slug: 'elaichi-rusk',
    description: 'Traditional cardamom-flavoured crispy rusk. Perfect for dipping in chai. Made with pure ghee and freshly ground elaichi.',
    shortDescription: 'Cardamom-flavoured crispy rusk with ghee',
    categorySlug: 'rusks-toasts',
    images: [
      { url: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&q=80', alt: 'Elaichi rusk', isPrimary: true },
    ],
    variants: [
      { size: '300g', weight: '300g', price: 99, sku: 'ER-300' },
      { size: '600g', weight: '600g', price: 179, sku: 'ER-600' },
    ],
    dietaryTags: ['eggless', 'veg'],
    isShippable: true,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: '60 days',
    sortOrder: 1,
    ratings: { average: 4.4, count: 389 },
  },

  // ===================== BEVERAGES =====================
  {
    name: 'Chocolate Shake',
    slug: 'chocolate-shake',
    description: 'Thick, creamy chocolate milkshake made with premium chocolate ice cream and fresh milk. Topped with whipped cream.',
    shortDescription: 'Thick & creamy chocolate milkshake',
    categorySlug: 'shakes',
    images: [
      { url: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=800&q=80', alt: 'Chocolate shake', isPrimary: true },
    ],
    variants: [
      { size: 'Regular (300ml)', weight: '300ml', price: 149, sku: 'CS-300' },
      { size: 'Large (500ml)', weight: '500ml', price: 199, sku: 'CS-500' },
    ],
    dietaryTags: ['veg'],
    isShippable: false,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: 'Serve immediately',
    sortOrder: 1,
    ratings: { average: 4.6, count: 234 },
  },
  {
    name: 'Cold Coffee',
    slug: 'cold-coffee',
    description: 'Creamy, frothy cold coffee blended with premium Arabica beans and fresh cream. Your perfect pick-me-up.',
    shortDescription: 'Creamy cold coffee with Arabica beans',
    categorySlug: 'coffee',
    images: [
      { url: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=800&q=80', alt: 'Cold coffee', isPrimary: true },
    ],
    variants: [
      { size: 'Regular (300ml)', weight: '300ml', price: 129, sku: 'CCF-300' },
      { size: 'Large (500ml)', weight: '500ml', price: 179, sku: 'CCF-500' },
    ],
    dietaryTags: ['veg'],
    isShippable: false,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: 'Serve immediately',
    isFeatured: true,
    sortOrder: 1,
    ratings: { average: 4.5, count: 312 },
  },
  {
    name: 'Fresh Orange Juice',
    slug: 'fresh-orange-juice',
    description: '100% freshly squeezed orange juice with no added sugar or preservatives. Pure, refreshing, and full of Vitamin C.',
    shortDescription: 'Freshly squeezed orange juice, no sugar',
    categorySlug: 'fresh-juices',
    images: [
      { url: 'https://images.unsplash.com/photo-1621506289937-a8e4df240d0b?w=800&q=80', alt: 'Fresh orange juice', isPrimary: true },
    ],
    variants: [
      { size: '300ml', weight: '300ml', price: 99, sku: 'FOJ-300' },
    ],
    dietaryTags: ['veg'],
    isShippable: false,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: 'Serve immediately',
    sortOrder: 1,
    ratings: { average: 4.3, count: 145 },
  },

  // ===================== FOOD MENU =====================
  {
    name: 'Classic Veg Burger',
    slug: 'classic-veg-burger',
    description: 'Crispy aloo tikki patty with fresh lettuce, tomato, onions, and our special sauce in a toasted sesame bun.',
    shortDescription: 'Crispy aloo tikki burger with special sauce',
    categorySlug: 'burgers',
    images: [
      { url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80', alt: 'Veg burger', isPrimary: true },
    ],
    variants: [
      { size: 'Regular', weight: '200g', price: 129, sku: 'CVB-R' },
      { size: 'Double', weight: '300g', price: 179, sku: 'CVB-D' },
    ],
    dietaryTags: ['veg'],
    isShippable: false,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: 'Serve immediately',
    sortOrder: 1,
    ratings: { average: 4.2, count: 278 },
  },
  {
    name: 'Margherita Pizza',
    slug: 'margherita-pizza',
    description: 'Classic Italian pizza with our house-made tomato sauce, fresh mozzarella, and fragrant basil on a thin, crispy crust.',
    shortDescription: 'Classic thin-crust Margherita pizza',
    categorySlug: 'pizza',
    images: [
      { url: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&q=80', alt: 'Margherita pizza', isPrimary: true },
    ],
    variants: [
      { size: 'Regular (8")', weight: '300g', price: 199, sku: 'MP-8' },
      { size: 'Large (12")', weight: '500g', price: 349, sku: 'MP-12' },
    ],
    dietaryTags: ['veg'],
    isShippable: false,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: 'Serve immediately',
    isFeatured: true,
    sortOrder: 1,
    ratings: { average: 4.4, count: 456 },
  },
  {
    name: 'Paneer Tikka Sandwich',
    slug: 'paneer-tikka-sandwich',
    description: 'Grilled paneer tikka with bell peppers, onions, and mint chutney in toasted multigrain bread.',
    shortDescription: 'Grilled paneer tikka multigrain sandwich',
    categorySlug: 'sandwiches',
    images: [
      { url: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&q=80', alt: 'Paneer tikka sandwich', isPrimary: true },
    ],
    variants: [
      { size: 'Regular', weight: '200g', price: 149, sku: 'PTS-R' },
    ],
    dietaryTags: ['veg'],
    isShippable: false,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: 'Serve immediately',
    sortOrder: 1,
    ratings: { average: 4.3, count: 167 },
  },

  // ===================== FESTIVE HAMPERS =====================
  {
    name: 'Diwali Premium Gift Hamper',
    slug: 'diwali-premium-gift-hamper',
    description: 'Exquisite Diwali gift box featuring assorted cookies, dry cakes, premium chocolates, and traditional sweets. Beautifully packaged in a designer box.',
    shortDescription: 'Premium Diwali gift box with assorted treats',
    categorySlug: 'festive-hampers',
    images: [
      { url: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&q=80', alt: 'Diwali gift hamper', isPrimary: true },
    ],
    variants: [
      { size: 'Standard', weight: '1kg', price: 999, compareAtPrice: 1299, sku: 'DPH-S' },
      { size: 'Premium', weight: '2kg', price: 1799, compareAtPrice: 2199, sku: 'DPH-P' },
      { size: 'Royal', weight: '3kg', price: 2799, compareAtPrice: 3499, sku: 'DPH-R' },
    ],
    dietaryTags: ['eggless', 'veg'],
    isShippable: true,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    shelfLife: '30 days',
    isFeatured: true,
    sortOrder: 1,
    ratings: { average: 4.8, count: 89 },
  },
];

module.exports = products;
