// Subscription Plan seed data
// Product references use slugs — resolved to ObjectIds in the seed runner

const subscriptionPlans = [
  {
    name: 'Protein Breakfast Box',
    slug: 'protein-breakfast-box',
    description: 'Start your mornings right with our curated selection of high-protein baked goods. Each box includes protein-packed muffins, energy cookies, and wholesome breakfast bars made with whey protein, oats, and nuts.',
    shortDescription: 'Start your day with high-protein muffins, cookies & energy bars.',
    image: 'https://images.unsplash.com/photo-1495147466023-ac5c588e2e94?w=600&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1495147466023-ac5c588e2e94?w=1200&q=80',
    planType: 'curated',
    lane: 'FRESH_CITY_ONLY',
    itemSlugs: [
      { slug: 'chocolate-chip-cookies-pack', variantIndex: 0, quantity: 1, isSwappable: true },
      { slug: 'classic-fudge-brownie', variantIndex: 0, quantity: 1, isSwappable: true },
      { slug: 'honey-almond-tea-cake', variantIndex: 0, quantity: 1, isSwappable: true },
    ],
    priceWeekly: 499,
    priceBiweekly: 899,
    priceMonthly: 1599,
    compareAtPriceMonthly: 1999,
    allowedFrequencies: ['weekly', 'biweekly', 'monthly'],
    swapRules: {
      requiredTags: [],
      mustMatchShelfLifeType: true,
      maxSwapsPerCycle: 2,
    },
    cutoffHoursBeforeDelivery: 24,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    isPanIndia: false,
    targetNutritionTags: ['high_protein', 'low_sugar'],
    isActive: true,
    isFeatured: true,
    sortOrder: 1,
    subscriberCount: 234,
  },
  {
    name: 'Low Sugar Snack Box',
    slug: 'low-sugar-snack-box',
    description: 'Satisfy your cravings without the sugar crash. Enjoy sugar-free brownies, almond biscuits, and keto-friendly muffins made with natural sweeteners like stevia and monk fruit.',
    shortDescription: 'Guilt-free snacking with sugar-free brownies, biscuits & bars.',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=1200&q=80',
    planType: 'curated',
    lane: 'FRESH_CITY_ONLY',
    itemSlugs: [
      { slug: 'classic-fudge-brownie', variantIndex: 0, quantity: 1, isSwappable: true },
      { slug: 'chocolate-chip-cookies-pack', variantIndex: 0, quantity: 1, isSwappable: true },
      { slug: 'elaichi-rusk', variantIndex: 0, quantity: 1, isSwappable: true },
    ],
    priceWeekly: 399,
    priceBiweekly: 749,
    priceMonthly: 1299,
    compareAtPriceMonthly: 1599,
    allowedFrequencies: ['weekly', 'biweekly', 'monthly'],
    swapRules: {
      requiredTags: [],
      mustMatchShelfLifeType: true,
      maxSwapsPerCycle: 2,
    },
    cutoffHoursBeforeDelivery: 24,
    availableInCities: ['Bhopal', 'Indore', 'Gwalior'],
    isPanIndia: false,
    targetNutritionTags: ['low_sugar', 'sugar_free'],
    isActive: true,
    isFeatured: true,
    sortOrder: 2,
    subscriberCount: 156,
  },
  {
    name: 'Weekend Bakery Basket',
    slug: 'weekend-bakery-basket',
    description: 'Make your weekends special with a fresh basket of artisan breads, buttery croissants, and wholesome pastries. Perfect for a leisurely brunch with family.',
    shortDescription: 'Artisan breads, croissants & pastries for your weekend brunch.',
    image: 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?w=600&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?w=1200&q=80',
    planType: 'curated',
    lane: 'FRESH_CITY_ONLY',
    itemSlugs: [
      { slug: 'butter-croissant', variantIndex: 0, quantity: 2, isSwappable: true },
      { slug: 'multigrain-bread-loaf', variantIndex: 0, quantity: 1, isSwappable: true },
      { slug: 'honey-almond-tea-cake', variantIndex: 0, quantity: 1, isSwappable: true },
    ],
    priceWeekly: 599,
    priceBiweekly: 1099,
    priceMonthly: 1999,
    compareAtPriceMonthly: 2499,
    allowedFrequencies: ['weekly', 'biweekly', 'monthly'],
    swapRules: {
      requiredTags: [],
      mustMatchShelfLifeType: true,
      maxSwapsPerCycle: 3,
    },
    cutoffHoursBeforeDelivery: 24,
    availableInCities: ['Bhopal', 'Indore'],
    isPanIndia: false,
    targetNutritionTags: ['whole_grain', 'organic'],
    isActive: true,
    isFeatured: true,
    sortOrder: 3,
    subscriberCount: 89,
  },
  {
    name: 'Office Snack Pack',
    slug: 'office-snack-pack',
    description: 'Keep your office pantry stocked with healthy shelf-stable snacks. Cookies, rusks, trail mixes, and energy bars shipped anywhere in India.',
    shortDescription: 'Shelf-stable cookies, rusks & trail mixes shipped anywhere in India.',
    image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=1200&q=80',
    planType: 'curated',
    lane: 'SHELF_STABLE_NATIONAL',
    itemSlugs: [
      { slug: 'chocolate-chip-cookies-pack', variantIndex: 0, quantity: 2, isSwappable: true },
      { slug: 'elaichi-rusk', variantIndex: 0, quantity: 1, isSwappable: true },
    ],
    priceWeekly: 349,
    priceBiweekly: 649,
    priceMonthly: 1099,
    compareAtPriceMonthly: 1399,
    allowedFrequencies: ['biweekly', 'monthly'],
    swapRules: {
      requiredTags: [],
      mustMatchShelfLifeType: true,
      maxSwapsPerCycle: 2,
    },
    cutoffHoursBeforeDelivery: 48,
    availableInCities: [],
    isPanIndia: true,
    targetNutritionTags: ['high_fiber', 'low_calorie'],
    isActive: true,
    isFeatured: true,
    sortOrder: 4,
    subscriberCount: 412,
  },
  {
    name: 'Healthy Morning Box',
    slug: 'healthy-morning-box',
    description: 'A nourishing pan-India box with granola, oat cookies, and dry fruit bars. Perfect for health-conscious mornings without compromising on taste.',
    shortDescription: 'Granola, oat cookies & dry fruit bars delivered pan-India.',
    image: 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=600&q=80',
    bannerImage: 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=1200&q=80',
    planType: 'curated',
    lane: 'SHELF_STABLE_NATIONAL',
    itemSlugs: [
      { slug: 'chocolate-chip-cookies-pack', variantIndex: 0, quantity: 1, isSwappable: true },
      { slug: 'elaichi-rusk', variantIndex: 0, quantity: 1, isSwappable: true },
      { slug: 'multigrain-bread-loaf', variantIndex: 0, quantity: 1, isSwappable: true },
    ],
    priceWeekly: 449,
    priceBiweekly: 849,
    priceMonthly: 1399,
    compareAtPriceMonthly: 1799,
    allowedFrequencies: ['biweekly', 'monthly'],
    swapRules: {
      requiredTags: [],
      mustMatchShelfLifeType: true,
      maxSwapsPerCycle: 2,
    },
    cutoffHoursBeforeDelivery: 48,
    availableInCities: [],
    isPanIndia: true,
    targetNutritionTags: ['high_fiber', 'gluten_free', 'vegan'],
    isActive: true,
    isFeatured: true,
    sortOrder: 5,
    subscriberCount: 178,
  },
];

module.exports = subscriptionPlans;
